language: ruby
rvm:
  - 2.5.8
services:
  - postgresql
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
env:
  global:
  - PGPORT=5433
  - PGUSER=travis

before_script:
  - cp config/database.yml.travis config/database.yml
  - "psql -c 'create database sppl_travis_test;' -U postgres"
  - "bundle exec rake db:migrate"

script: bundle exec rake test
